"""Input records, parameters and output records of the MRP engine.

Everything here is a plain dataclass so the engine stays independent from pandas, the
database layer and the API layer.  Quantities are floats (units may be KG or M).
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Literal


# =============================================================================
# Reference data
# =============================================================================
@dataclass
class Article:
    article_id: str
    designation: str = ""
    unit: str = "PCE"
    family: str = ""
    planner: str = ""
    coverage_target_days: int = 7
    alert_red_days: int = 3
    alert_yellow_days: int = 7
    overstock_days: int = 30
    safety_stock_qty: float = 0.0
    lot_policy: Literal["coverage", "poq", "fixed_lot"] = "coverage"
    order_cycle_days: int = 7
    fixed_lot_qty: float = 0.0
    active: bool = True
    service_rate_tracked: bool = False
    dhrq: str = ""


@dataclass
class Supplier:
    supplier_id: str
    name: str = ""
    country: str = ""
    contact: str = ""
    delivery_weekdays: frozenset[int] = frozenset({1, 2, 3, 4, 5})
    calendar_id: str = "DEFAULT"
    active: bool = True


@dataclass
class SupplierLink:
    """Article ↔ supplier sourcing rule (MOQ, packaging, lead time, quota)."""

    article_id: str
    supplier_id: str
    moq: float = 0.0
    pack_qty: float = 0.0  # "PLA" – packaging / rounding quantity
    lead_time_days: int = 10  # working days
    quota_pct: float = 100.0
    priority: int = 1
    active: bool = True


@dataclass
class Program:
    program_id: str
    name: str = ""
    family: str = ""
    active: bool = True


@dataclass
class BomLine:
    program_id: str
    article_id: str
    qty_per: float
    unit: str = "PCE"
    scrap_pct: float = 0.0
    valid_from: dt.date | None = None
    valid_to: dt.date | None = None


# =============================================================================
# Facts
# =============================================================================
@dataclass
class PlanLine:
    """Weekly production plan (PDP) for one program and one ISO week."""

    program_id: str
    week_start: dt.date  # Monday
    qty: float
    version: str = ""


@dataclass
class ActualLine:
    """Actual daily production reported for a program (overrides the plan for that day)."""

    program_id: str
    date: dt.date
    qty: float


class OrderType(str, Enum):
    FIRM = "FIRM"  # confirmed schedule line / purchase order (DELJIT, PO)
    FORECAST = "FORECAST"  # forecast schedule line (DELFOR)
    PLANNED = "PLANNED"  # planned in the app, not sent to the supplier
    PROPOSAL = "PROPOSAL"  # generated by the engine


class OrderStatus(str, Enum):
    OPEN = "OPEN"
    PARTIAL = "PARTIAL"
    RECEIVED = "RECEIVED"
    CLOSED = "CLOSED"  # closed short: remainder will not be delivered
    CANCELLED = "CANCELLED"


@dataclass
class OrderLine:
    order_id: str
    article_id: str
    supplier_id: str | None
    expected_date: dt.date
    qty_ordered: float
    qty_received: float = 0.0
    order_type: OrderType = OrderType.FIRM
    status: OrderStatus = OrderStatus.OPEN
    source: str = "ERP"  # ERP | APP | SCENARIO | PROPOSAL
    order_date: dt.date | None = None
    note: str = ""

    @property
    def qty_open(self) -> float:
        if self.status in (OrderStatus.RECEIVED, OrderStatus.CLOSED, OrderStatus.CANCELLED):
            return 0.0
        return max(0.0, self.qty_ordered - self.qty_received)


@dataclass
class Receipt:
    receipt_id: str
    article_id: str
    receipt_date: dt.date
    qty: float
    supplier_id: str | None = None
    order_id: str | None = None
    source: str = "ERP"


@dataclass
class Movement:
    """Stock adjustment (inventory count, scrap, transfer…) dated after the snapshot."""

    movement_id: str
    article_id: str
    date: dt.date
    qty: float
    movement_type: str = "INVENTORY_ADJUSTMENT"
    source: str = "ERP"
    comment: str = ""


@dataclass
class SimCell:
    """One editable cell of the simulation grid (planner entry or CBN result).

    ``kind`` = ``sim_order`` (simulated order, signed quantity, counted in the *simulated* stock
    only) or ``adjustment`` (signed stock adjustment counted in every layer).
    """

    article_id: str
    date: dt.date
    kind: Literal[
        "sim_order",
        "adjustment",
        "demand",
        "firm_flow",
        "forecast_flow",
        "planned_flow",
        "receipt_flow",
        "adjustment_flow",
    ]
    qty: float
    source: str = "MANUAL"  # MANUAL | CBN | IMPORT
    note: str = ""


@dataclass
class StockSnapshot:
    article_id: str
    snapshot_date: dt.date  # stock known at the END of this day
    qty_on_hand: float
    qty_blocked: float = 0.0


@dataclass
class Dataset:
    """Everything the engine needs, as plain records."""

    articles: list[Article]
    suppliers: list[Supplier]
    links: list[SupplierLink]
    programs: list[Program]
    bom: list[BomLine]
    plan: list[PlanLine]
    actuals: list[ActualLine]
    orders: list[OrderLine]
    receipts: list[Receipt]
    movements: list[Movement]
    stock: list[StockSnapshot]
    holidays: list[dt.date] = field(default_factory=list)
    cells: list[SimCell] = field(default_factory=list)
    meta: dict[str, Any] = field(default_factory=dict)


# =============================================================================
# Parameters
# =============================================================================
@dataclass
class EngineParams:
    """All business rules that are configurable (see docs/regles_metier.md)."""

    as_of: dt.date | None = None  # default: max stock snapshot date + 1
    horizon_days: int = 120  # projection horizon after as_of
    history_days: int = 14  # days before as_of kept in the output series
    working_weekdays: tuple[int, ...] = (1, 2, 3, 4, 5)

    # Demand
    spread_rounding: Literal["none", "exact", "per_day"] = "exact"
    production_mode: Literal["actual_then_plan", "plan_only", "actual_only"] = "actual_then_plan"
    missing_actual_policy: Literal["plan", "zero"] = "plan"
    consumption_offset_days: int = 0  # <0: components consumed before the production day

    # Supply – three cumulative stock layers: firm ⊂ forecast ⊂ simulated
    firm_sources: tuple[str, ...] = ("FIRM",)  # order types in the *firm* stock
    forecast_sources: tuple[str, ...] = ("FORECAST",)  # added to the firm flows → *forecast* stock
    simulated_sources: tuple[str, ...] = ("PLANNED",)  # added to the forecast flows → *simulated* stock
    app_firm_orders: Literal["firm", "simulated"] = "firm"  # app orders marked sent: firm layer, or simulation only
    include_proposals_in_simulation: bool = True
    late_order_policy: Literal["reschedule", "ignore", "keep"] = "reschedule"
    orders_source: Literal["merged", "erp", "app"] = "merged"

    # Coverage / stock policy
    shortage_policy: Literal["backlog", "lost"] = "backlog"  # unserved demand: carried forward or lost
    coverage_unit: Literal["calendar", "working"] = "calendar"
    lead_calendar: Literal["calendar", "working"] = "working"
    receipt_timing: Literal["before_demand", "after_demand"] = "before_demand"
    coverage_tie_rule: Literal["covered", "not_covered"] = "covered"
    target_policy: Literal["coverage_days", "safety_qty", "max", "sum"] = "max"

    # Proposals (net requirements): computed on demand by the "Calcul CBN" action, not on every run
    generate_proposals: bool = False
    frozen_days: int = 0
    respect_lead_time: bool = True  # True: never propose a delivery before as_of + lead time
    delivery_shift: Literal["earlier", "later"] = "earlier"
    sourcing_policy: Literal["quota", "priority"] = "quota"
    proposal_lookahead_days: int | None = None  # None: whole horizon

    # Alerts
    stockout_lookahead_days: int | None = None  # None: whole horizon
    firm_horizon_days: int = 28  # firm-flow stockouts beyond this are informational

    def copy_with(self, **changes: Any) -> "EngineParams":
        data = self.__dict__.copy()
        data.update(changes)
        return EngineParams(**data)


# =============================================================================
# Outputs
# =============================================================================
class AlertType(str, Enum):
    STOCKOUT = "STOCKOUT"
    LOW_COVERAGE = "LOW_COVERAGE"
    OVERSTOCK = "OVERSTOCK"
    LATE_ORDER = "LATE_ORDER"
    URGENT_PROPOSAL = "URGENT_PROPOSAL"
    NO_DEMAND = "NO_DEMAND"
    MISSING_DATA = "MISSING_DATA"
    NEGATIVE_STOCK = "NEGATIVE_STOCK"


class Severity(str, Enum):
    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"


@dataclass
class Alert:
    article_id: str
    alert_type: AlertType
    severity: Severity
    message: str
    date: dt.date | None = None
    value: float | None = None
    scope: Literal["firm", "forecast", "simulated", "data"] = "simulated"
    details: dict[str, Any] = field(default_factory=dict)


@dataclass
class Proposal:
    proposal_id: str
    article_id: str
    supplier_id: str | None
    delivery_date: dt.date
    order_date: dt.date
    qty: float
    net_requirement: float
    reason: str
    urgent: bool = False
    lead_time_days: int = 0
    moq: float = 0.0
    pack_qty: float = 0.0
    projected_stock_before: float = 0.0
    projected_stock_after: float = 0.0


@dataclass
class SupplyEvent:
    """One dated supply element shown in the article table / tooltips."""

    date: dt.date
    kind: str  # order | sim_order | receipt | movement | proposal
    ref: str
    qty: float
    supplier_id: str | None
    order_type: str
    source: str
    late: bool = False


@dataclass
class ArticleResult:
    article: Article
    start_date: dt.date
    as_of: dt.date
    dates: list[dt.date]
    # daily series aligned on ``dates``
    demand: list[float]
    demand_plan: list[float]
    demand_actual_share: list[float]
    supply_firm: list[float]  # committed orders
    supply_forecast: list[float]  # ERP forecast schedule lines
    supply_planned: list[float]  # app / scenario planned orders (not sent)
    supply_proposed: list[float]  # engine proposals
    receipts: list[float]
    adjustments: list[float]
    # physical stocks (never negative), unserved demand and net balances per layer
    stock_firm: list[float]
    stock_forecast: list[float]
    stock_sim: list[float]
    shortage_firm: list[float]
    shortage_forecast: list[float]
    shortage_sim: list[float]
    stock_firm_net: list[float]
    stock_forecast_net: list[float]
    stock_sim_net: list[float]
    coverage_firm: list[int]
    coverage_forecast: list[int]
    coverage_sim: list[int]
    target_stock: list[float]
    events: list[SupplyEvent]
    alerts: list[Alert]
    proposals: list[Proposal]
    kpis: dict[str, Any]
    suppliers: list[SupplierLink]
    diagnostics: list[str] = field(default_factory=list)


@dataclass
class MrpResult:
    as_of: dt.date
    start_date: dt.date
    end_date: dt.date
    params: EngineParams
    articles: dict[str, ArticleResult]
    program_daily: dict[str, dict[dt.date, float]]
    tail_dates: list[dt.date] = field(default_factory=list)
    tail_demand: dict[str, list[float]] = field(default_factory=dict)
    diagnostics: list[str] = field(default_factory=list)

    @property
    def alerts(self) -> list[Alert]:
        return [a for r in self.articles.values() for a in r.alerts]

    @property
    def proposals(self) -> list[Proposal]:
        return [p for r in self.articles.values() for p in r.proposals]
