"""Versioned Excel interchange. All input cells are values; formulas are rejected.
Output calculations are regenerated by the server, never trusted on reimport.
"""
from io import BytesIO
import json
import zipfile
from datetime import date,datetime,timedelta
from decimal import Decimal
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from .models import Dataset

TABLES=[k for k in Dataset.model_fields if k!='settings']
MAX_BYTES=10*1024*1024

def export_workbook(data:Dataset,result:dict,item_ids:set|None=None,granularity='day')->bytes:
    if granularity not in ('day','week','month'):raise ValueError('Granularité inconnue')
    wb=openpyxl.Workbook();wb.remove(wb.active)
    def sheet(name,records,headers=None):
        ws=wb.create_sheet(name);headers=headers or (list(records[0]) if records else ['information'])
        ws.append(headers)
        for record in records:
            values=[]
            for k in headers:
                v=record.get(k)
                if isinstance(v,(dict,list)):v=json.dumps(v,ensure_ascii=False)
                if isinstance(v,Decimal):v=float(v)
                values.append(v)
            ws.append(values)
            for c in ws[ws.max_row]:
                if isinstance(c.value,str):c.data_type='s' # prevent formula injection in names/reasons
        ws.freeze_panes='A2';ws.auto_filter.ref=ws.dimensions
        for c in ws[1]:c.font=Font(color='FFFFFF',bold=True);c.fill=PatternFill('solid',fgColor='163B43')
        for col in ws.columns:
            ws.column_dimensions[col[0].column_letter].width=min(48,max(16,max(len(str(c.value or '')) for c in col[:100])+2))
        return ws
    sheet('README',[{'Champ':'Format','Valeur':'PROCUREMENT/1'},{'Champ':'Mode','Valeur':'Les feuilles inputs_* sont complètes et réimportables. Les outputs_* sont filtrés et recalculés.'},{'Champ':'Stock initial','Valeur':'Début de journée settings.start. Changer la date exige de recaler stock et reçus antérieurs.'},{'Champ':'Granularité','Valeur':granularity}])
    sheet('settings',[{'key':k,'value':json.dumps(v,ensure_ascii=False)} for k,v in data.settings.model_dump(mode='json').items()])
    for name in TABLES:
        model=Dataset.model_fields[name].annotation.__args__[0]
        sheet('inputs_'+name,[r.model_dump(mode='json') for r in getattr(data,name)],list(model.model_fields))
    selected=lambda r:item_ids is None or r['item_id'] in item_ids
    series=[r for r in result['series'] if selected(r)]
    if granularity!='day':
        grouped={}
        for row in series:
            d=date.fromisoformat(row['date']);period=str(d-timedelta(days=d.weekday())) if granularity=='week' else d.strftime('%Y-%m')
            key=(row['item_id'],period)
            if key not in grouped:grouped[key]={**row,'date':period}
            else:
                g=grouped[key]
                for field in ['demand','receipts','draft_receipts','adjustment']:g[field]+=row[field]
                for field in ['stock','simulated','target','coverage','coverage_censored','status']:g[field]=row[field]
        series=list(grouped.values())
    sheet('outputs_series',series);sheet('outputs_alerts',[r for r in result['alerts'] if selected(r)])
    sheet('outputs_proposals',[r for r in result['proposals'] if selected(r)])
    sheet('outputs_orders',[o.model_dump(mode='json') for o in data.orders if item_ids is None or o.item_id in item_ids])
    out=BytesIO();wb.save(out);return out.getvalue()

def read_workbook(content:bytes)->Dataset:
    if len(content)>MAX_BYTES:raise ValueError('Fichier supérieur à 10 Mo')
    try:
        with zipfile.ZipFile(BytesIO(content)) as archive:
            if sum(f.file_size for f in archive.infolist())>80*1024*1024 or len(archive.infolist())>300:
                raise ValueError('Classeur trop volumineux après décompression')
        wb=openpyxl.load_workbook(BytesIO(content),read_only=True,data_only=False,keep_links=False)
    except (zipfile.BadZipFile,KeyError):raise ValueError('Fichier XLSX invalide')
    try:
        if 'README' not in wb or wb['README']['B2'].value!='PROCUREMENT/1':raise ValueError('Format attendu : export PROCUREMENT/1')
        def records(name):
            if name not in wb:raise ValueError(f'Feuille manquante : {name}')
            ws=wb[name]
            if ws.max_row>50001 or ws.max_column>40:raise ValueError('Dimensions excessives')
            values=[];it=iter(ws.rows);heads=[c.value for c in next(it)]
            if len(set(heads))!=len(heads):raise ValueError('En-têtes dupliqués')
            for row in it:
                if all(c.value is None for c in row):continue
                if any(c.data_type=='f' for c in row):raise ValueError(f'Formule interdite dans {name}')
                values.append({k:(c.value.date().isoformat() if isinstance(c.value,datetime) else c.value) for k,c in zip(heads,row) if c.value is not None})
            return values
        setting_rows=records('settings')
        if len({r['key'] for r in setting_rows})!=len(setting_rows):raise ValueError('Paramètres settings dupliqués')
        settings={r['key']:json.loads(str(r['value'])) for r in setting_rows}
        return Dataset.model_validate({'settings':settings,**{k:records('inputs_'+k) for k in TABLES}})
    finally:wb.close()

def read_pdp(content:bytes)->list[dict]:
    """Long-format CSV only; Excel full roundtrip is handled separately."""
    import csv
    from .models import Plan
    if len(content)>MAX_BYTES:raise ValueError('Fichier supérieur à 10 Mo')
    text=content.decode('utf-8-sig')
    try:dialect=csv.Sniffer().sniff(text[:4096],delimiters=',;\t')
    except csv.Error:raise ValueError('CSV invalide : utiliser program,week,quantity')
    rows=list(csv.DictReader(text.splitlines(),dialect=dialect))
    if len(rows)>50000:raise ValueError('Trop de lignes PDP')
    return [Plan.model_validate(r).model_dump(mode='json') for r in rows]
